server:
  port: 5100
spring:
  application:
    name: virsical-map
#  jackson:
#    default-property-inclusion: non_null
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/virsical_map?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root

# mybatis-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false

# 租户表维护
tenant:
  tables:
    - park
    - building
    - floor
    - map
    - svg
    - svg_state

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# 日志文件
logging:
  file: ${user.dir}/logs/${spring.application.name}-${server.port}.log
  level:
    root: info
    com.wafersystems.virsical.map.mapper: debug

# 推送服务地址
push:
  service:
    enable: false
    url: http://localhost:5200/send/